schema_version: 1

context:
  python_min: "3.12"
  version: "0.29.0"

package:
  name: wsidicomizer
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wsidicomizer/wsidicomizer-${{ version }}.tar.gz
  sha256: ae7426bbe9bf6bf4c25041a3df5aa5b5d6aebb961f1ac83c6ec9fcc92d2a1408

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - wsidicomizer = wsidicomizer.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - wsidicom >=0.34.0,<0.35.0
    - opentile >=0.24.0,<0.25.0
    - numpy >=1.22.0
    - pydicom >=3.0.0
    - czifile >=2026.3.12
    - tiffslide >=4.0.0,<5.0.0
    - click >=8.3.0,<9.0.0

tests:
  - python:
      imports:
        - wsidicomizer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - wsidicomizer --help

about:
  summary: Tool for reading WSI files from proprietary formats and optionally convert them to to DICOM
  license: Apache-2.0
  license_file: LICENCE
  homepage: https://pypi.org/project/wsidicomizer/

extra:
  recipe-maintainers:
    - sarthakpati
